## Request callback [/callback]

## Request a callback [POST]

+ Request (application/json)

    + Body

            {
                "target": ["contact_person"]
            }

+ Response 200 (application/json)
