## Device [/device]

## Add device [POST]

+ Request (application/json)

    + Body

            {
                "provider": "apple", - apple vagy google
                "device_token": "device_token_string"
            }

+ Response 200 (application/json)
