FORMAT: 1A
HOST: http://whc-vote-be.dev.clapp.eu/api/1.0

# WHC Vote

- Minden http request `Content-type: application/json`-t küld és fogad, kivéve, ha mást írunk lentebb
- Minden API endpoint standard http headerekkel és http hibakódokkal dolgozik
- Ha a kliensnek van auth tokene (azaz “be van jelentkezve”), akkor minden további http requesthez csatolnia kell egy `Authorization: Bearer <auth token>` headert

<!-- include(auth.apib) -->

<!-- include(user.apib) -->
<!-- include(user/import.apib) -->
<!-- include(user/notification.apib) -->
<!-- include(user/rating_period.apib) -->
<!-- include(user/rating_period/rating_target.apib) -->
<!-- include(user/rating_period/rating/rating.apib) -->

<!-- include(static_content.apib) -->

<!-- include(rating_period.apib) -->

<!-- include(role.apib) -->

<!-- include(news.apib) -->

<!-- include(question.apib) -->
<!-- include(question/answer.apib) -->

<!-- include(callback.apib) -->

<!-- include(device.apib) -->

<!-- include(importjob.apib) -->

<!-- include(data_structures/data.apib) -->
<!-- include(data_structures/pager.apib) -->
<!-- include(data_structures/user.apib) -->
<!-- include(data_structures/notification.apib) -->
<!-- include(data_structures/rating.apib) -->
<!-- include(data_structures/static_content.apib) -->
<!-- include(data_structures/image.apib) -->
<!-- include(data_structures/role.apib) -->
<!-- include(data_structures/news.apib) -->
<!-- include(data_structures/question.apib) -->
<!-- include(data_structures/rating_period.apib) -->
<!-- include(data_structures/importjob.apib) -->
