## Question [/role/{role_id}/question]

### List Questions [GET /role/{role_id}/question{?page}]

+ Parameters
    + role_id (required, enum[string]) - User role
        + Members
            + accountant
            + hr
            + accountant_client
            + hr_client
            + business_partner
    + page (optional, number, `1`)

+ Response 200 (application/json)

    + Attribute (QuestionPager)

### Get a single question [GET /role/{role_id}/question/{question_id}]

+ Parameters
    + role_id (required, enum[string]) - User role
        + Members
            + accountant
            + hr
            + accountant_client
            + hr_client
            + business_partner
    + question_id (required, number, `1`)

+ Response 200 (application/json)

    + Attribute (QuestionDetailed)

+ Response 404 (application/json)
