## Static content [/static_content]

### Terms and conditions [GET /static_content/terms]

+ Response 200 (application/json)

    + Attribute(Static_terms)

### Privacy policy [GET /static_content/privacy]

+ Response 200 (application/json)

    + Attribute(Static_privacy)
