## Image (object)
+ small: `http://127.0.0.1:3333/image/small/news/6l/ed/6led9krl0qg5z8m33vdddd598mp6w2x4v31n7o7q.jpg` (required, string)
+ medium: `http://127.0.0.1:3333/image/medium/news/6l/ed/6led9krl0qg5z8m33vdddd598mp6w2x4v31n7o7q.jpg` (required, string)
+ large: `http://127.0.0.1:3333/image/large/news/6l/ed/6led9krl0qg5z8m33vdddd598mp6w2x4v31n7o7q.jpg` (required, string)
+ original: `http://127.0.0.1:3333/image/original/news/6l/ed/6led9krl0qg5z8m33vdddd598mp6w2x4v31n7o7q.jpg` (required, string)
