## ImportJobPager (object)
+ Include Pager
+ data: ImportJob, ImportJob (array[ImportJob], required)

## ImportJob (object)
+ id: 1 (number, required)
+ whc_progress: 0.0 (number, required)
+ bp_progress: 0.0 (number, required)
+ user_progress: 0.0 (number, required)
+ target_progress: 0.0 (number, required)
+ overall_progress: 0.0 (number, required)
+ finished: false (boolean, required)
+ message: null (required)  // JSON
+ error: null (required)    // JSON
