## NewsPager
+ Include Pager
+ data: News, News (array[News], required)

## News (object)
+ id: 1 (number)
+ title: `News Title` (required, string)
+ image: `http://ichef.bbci.co.uk/news/976/cpsprodpb/7F89/production/_86594623_thinkstockphotos-473333164.jpg` (optional, string)
+ published_by: `WHC csapata` (required, string)
+ published_at: `2017-02-08 09:09:09` (required, string)

## NewsDetailed (object)
+ Include News
+ lead: `News lead` (optional, string)
+ content: `<p>News content</p>` (required, string) - HTML formatted string
