## NewsPager
+ Include Pager
+ data: News, News (array[News], required)

## News (object)
+ id: 1 (number, required)
+ title: `News Title` (required, string)
+ image_url (optional)
    Include Image
+ published_by: `WHC csapata` (required, string)
+ published_at: `2017-02-08 09:09:09` (required, string)

## NewsDetailed (object)
+ Include News
+ content: `<p>News content</p>` (required, string) - HTML formatted string
