## NotificationPager (object)
+ Include Pager
+ data: TargetNotification, TargetNotification (array[TargetNotification], required)

## BaseNotification (object)
+ id: 1 (number, required)
+ unseen: true (boolean, optional) - Először kérdezi le a szervertől a kliens ezt a Notification-t
+ type: `rating` (enum[string], required)
    + Members
        + rating
        + call_back
+ created_at: `2018-05-31 12:00:00` (string, required) - Létrehozási dátum
+ expiring_at: `2018-06-02 12:00:00` (string, optional) - Lejárati dátum

## TargetNotification (object)
+ Include BaseNotification
+ target
    Include BaseUser
