## QuestionPager
+ Include Pager
+ data: Question, Question (array[Question], required)

## Question (object)
+ id: 1 (number, required)
+ text: `Favourite programming language?` (string, required)
+ image: `http://ichef.bbci.co.uk/news/976/cpsprodpb/7F89/production/_86594623_thinkstockphotos-473333164.jpg` (string, optional)
+ published_by: `WHC csapata` (string, required)
+ published_at: `2017-02-08 09:09:09` (string, required)
+ expired: false (boolean, required)
+ voted: false (boolean, required)

## QuestionDetailed (object)
+ Include Question
+ answers: Answer, Answer, Answer, Answer (array[Answer], required)

## Answer (object)
+ id: 1 (number, required)
+ text: `Swift` (string, required)

## QuestionAnswered (object)
+ Include Question
+ answers: AnswerResult, AnswerResult, AnswerResult, AnswerResult (array[AnswerResult], required)

## AnswerResult (object)
+ Include Answer
+ result: 12.5 (number, optional)
+ selected: true (boolean, optional)
