## RatingPeriodPager
+ Include Pager
+ data: RatingPeriod, RatingPeriod (array[RatingPeriod], required)

## RatingPeriod (object)
+ id: 1 (number, required)
+ from: `2019-04-05 06:00:00` (string, required)
+ to: `2019-05-05 05:59:59` (string, required)
