## `Static_terms`
+ title: `Terms and conditions` (required, string)
+ slug: `terms` (required, string)
+ content: `<p>Terms and conditions content</p>` (required, string) - HTML formatted string

## `Static_privacy`
+ title: `Privacy policy` (required, string)
+ slug: `privacy` (required, string)
+ content: `<p>Privacy policy content</p>` (required, string) - HTML formatted string
