## UserPager (object)
+ Include Pager
+ data: ExtendedUser, ExtendedUser (array[ExtendedUser], required)

## BaseUser (object)
+ id: 7 (number, required)
+ name: `Lastname Firstname` (string, optional)
+ organization: false (boolean, required)
+ profile_pic_url: `https://whc.hu/profile/user7.jpg` (string, optional)
+ phone_number: `+3612345678` (string, optional) - Nemzetközi formátumban szóköz, kötöjel és zárójel nélkül

## ExtendedUser (object)
+ Include BaseUser
+ email: `user@whc.hu` (string, required)
+ request_notification: true (boolean, required)
+ request_news_notification: true (boolean, optional)
+ request_level_notification: true (boolean, optional)
+ level: 0 (number, required)
+ points: 0 (number, required)
+ required_points_for_next_level: 1000 (number, required)
