## UserPager (object)
+ Include Pager
+ data: User, User (array[User], required)

## User (object)
+ id: 7 (number, required)
+ email: `user@whc.hu` (string, optional)
+ request_notification: true (boolean, required)
