## UserPager (object)
+ Include Pager
+ data: ExtendedUser, ExtendedUser (array[ExtendedUser], required)

## BaseUser (object)
+ id: 7 (number, required)
+ name: `Lastname Firstname` (string, optional)
+ profile_pic_url: `https://whc.hu/profile/user7.jpg` (string, optional)
+ phone_number: `+3612345678` (string, optional)

## ExtendedUser (object)
+ email: `user@whc.hu` (string, required)
+ request_notification: true (boolean, required)
+ level: `beginner` (enum[string], required)
    + Members
        + beginner
        + advanced
        + master
+ points: 0 (number, required)
+ required_points_for_next_level: 10 (number, required)
