## User rating [/user/{user_id}/rating_period/{rating_period_id}/rating_target/{rating_target_id}/rating]

+ Parameters
    + user_id (required, number, `1`) - User ID
    + rating_period_id (required, number, `1`) - Rating Period ID
    + rating_target_id (required, number, `1`) - Rating target User ID

## Add rating [POST]

+ Request (application/json)

    + Attribute(Rating)

+ Response 200 (application/json)
