## Notification [/user/{user_id}/notification]

+ Parameters
    + user_id (required, number, `1`) - User ID

### Get new notification count [HEAD]

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Notification-Count: 3 (number, required)

### List user's notifications [GET /user/{user_id}/notification?{page}]

+ Parameters
    + user_id (required, number, `1`) - User ID
    + page (optional, number) - Oldalszám

+ Request (application/json)

+ Response 200 (application/json)

    + Attribute(NotificationPager)

### Remove notification [DELETE /user/{user_id}/notification/{notification_id}]

+ Parameters
    + user_id (required, number, `1`) - User ID
    + notification_id (required, number, `1`) - Notification ID

+ Response 200 (application/json)
