## User rating [/user/{user_id}/rating]

+ Parameters
    + user_id (required, number, `1`) - User ID

## Add rating [POST]

+ Request (application/json)

    + Attribute(Rating)

+ Response 200 (application/json)
